### ISSUE TITLE
Getting errors while pip setup.py install

### ISSUE THREAD

**Issue by gurdeepmaurya** [davisvideochallenge/davis2017-evaluation#11]
python setup.py install

/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/dist.py:760: UserWarning: Usage of dash-separated 'author-email' will not be supported in future versions. Please use the underscore name 'author_email' instead
  % (opt, underscore_opt)
/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/dist.py:760: UserWarning: Usage of dash-separated 'home-page' will not be supported in future versions. Please use the underscore name 'home_page' instead
  % (opt, underscore_opt)
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    'tqdm>=4.28.1'
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 122, in setup
    dist.parse_config_files()
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/dist.py", line 851, in parse_config_files
    self, self.command_options, ignore_option_errors=ignore_option_errors
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 167, in parse_configuration
    meta.parse()
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 446, in parse
    section_parser_method(section_options)
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 417, in parse_section
    self[name] = value
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 238, in __setitem__
    value = parser(value)
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 552, in _parse_version
    return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 371, in _parse_attr
    package_dir.update(self.ensure_discovered.package_dir)
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/config/expand.py", line 458, in __iter__
    return iter(self._target())
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/config/expand.py", line 448, in _target
    self._value = self._obtain()
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/config/expand.py", line 418, in _get_package_dir
    self()
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/config/expand.py", line 408, in __call__
    self._dist.set_defaults(name=False)  # Skip name, we can still be parsing
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/discovery.py", line 330, in __call__
    self._analyse_package_layout(ignore_ext_modules)
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/discovery.py", line 363, in _analyse_package_layout
    or self._analyse_flat_layout()
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/discovery.py", line 420, in _analyse_flat_layout
    return self._analyse_flat_packages() or self._analyse_flat_modules()
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/discovery.py", line 426, in _analyse_flat_packages
    self._ensure_no_accidental_inclusion(top_level, "packages")
  File "/home/zeus/anaconda3/envs/vfs/lib/python3.7/site-packages/setuptools/discovery.py", line 455, in _ensure_no_accidental_inclusion
    raise PackageDiscoveryError(cleandoc(msg))
setuptools.errors.PackageDiscoveryError: Multiple top-level packages discovered in a flat-layout: ['pytest', 'results', 'davis2017'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.

**Comment by yoxu515** [comment]
hi, you may try adding packages=['davis2017'] in the setup function argument to avoid multiple package conflict.

**Comment by andlyu** [comment]
Tried running `python setup.py install packages=['davis2017']` and got `zsh: no matches found: packages=[davis2017]`

**Comment by andlyu** [comment]
Update: just had to modify line 20 in setup.py to be the following : \
`    ],packages=['davis2017'])
`

**Comment by gurdeepmaurya** [comment]
@andlyu Could you please inform me whether you are able to reproduce their results with Resnet18 backbone on Davis benchmark? The best accuracy that I got on my implementation of this paper was 65.36 (J&Fmean).

**Comment by andlyu** [comment]
I was running evaluations on the XMem model, and was able to reporoduce their 2017 results using this evaluation. I didn't run this paper's model.

Link to XMem:  https://github.com/hkchengrex/XMem/blob/main/README.md

**Comment by gurdeepmaurya** [comment]
Confirming this solution works

https://github.com/davisvideochallenge/davis2017-evaluation/issues/11#issuecomment-1336366024
